# Generated by Django 4.0.5 on 2022-08-07 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book_outlet", "0007_address_author_address"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name_plural": "Address Entries"},
        ),
    ]
